Feature/downloading youtube videos
CouncilDataProject/cdp-backend pull request #169
Opened 2022-02-21 06:38 UTC by Shak2000

### Link to Relevant Issue

This pull request resolves #161 

### Description of Changes

Make it possible for the program to download a YouTube video embedded onto a website. This is needed for the Portland scraper.

2022-02-22 02:30 UTC, isaacna commented on cdp_backend/utils/file_utils.py
> +def youtube_copy(youtube_url: str, output: str) -> str:
We should consider `output` as `Optional[str]` and if there's no output name specified, hashing by the file contents. 

This would keep things similar to how we hash other files here: https://github.com/CouncilDataProject/cdp-backend/commit/873dddbcbfb6051c1c29d5cf9deab2eea4aa549a

@JacksonMaxfield thoughts?

2022-02-22 02:38 UTC, isaacna commented on cdp_backend/utils/file_utils.py
> +    if output[len(output) - 4 : len(output)] != ".mp4":
I think it'd be cleaner to check the extension like this: https://github.com/CouncilDataProject/cdp-backend/blob/main/cdp_backend/pipeline/event_gather_pipeline.py#L323-L327

2022-02-22 02:40 UTC, isaacna commented on cdp_backend/utils/file_utils.py
> +        if uri.find("https://www.youtube.com/embed/") == 0:
Can we expand this to run on youtube url's without `/embed` as well? The portland use case might only contain embedded videos, but we should try to make this function more flexible for future use cases

2022-02-22 02:41 UTC, isaacna requested changes
Looks good overall! Just had a few comments about naming the file and accepting more url formats

2022-02-22 03:15 UTC, JacksonMaxfield commented on cdp_backend/tests/utils/test_file_utils.py
> +def test_youtube_downloader(
Can you add this `skipif` to this test: https://github.com/CouncilDataProject/cdp-backend/blob/f95304853f01ce9d59db608dffd68a4099fbe539/cdp_backend/tests/database/test_validators.py#L85

Don't want to run this test if the person doesn't have internet available... (I code of the train a lot)

2022-02-22 03:15 UTC, JacksonMaxfield commented on cdp_backend/utils/file_utils.py
> +        if uri.find("https://www.youtube.com/embed/") == 0:
Completely agree. I think there are multiple paths we want to check:

The base youtube.com and the youtube url shortener "youtu.be"

2022-02-22 03:15 UTC, JacksonMaxfield commented on cdp_backend/utils/file_utils.py
> +def youtube_copy(youtube_url: str, output: str) -> str:
I think my general comment is that I think this function should be folded into `resource_copy`? Maybe keep it as a separate function for now but _use_ the function in `resource_copy` so that that single function can be used to fetch all sorts of content.

2022-02-22 03:15 UTC, JacksonMaxfield commented on cdp_backend/utils/file_utils.py
> +def youtube_copy(youtube_url: str, output: str) -> str:
Additionally, yes, if we could mirror the API of `resource_copy` that would be great. `output` -> renamed to `dst` and add an `overwrite` param as well.

Iirc, the `resource_copy` API matches the fsspec `.get` API so if they all match we can somewhat use them interchangably.

2022-02-22 03:15 UTC, JacksonMaxfield commented on cdp_backend/utils/file_utils.py
> +    if output[len(output) - 4 : len(output)] != ".mp4":
Agree but I will say that if this is folded into / used directly in the `resource_copy` function then hopefully we don't need to have duplicate code.

2022-02-22 23:22 UTC, isaacna commented on cdp_backend/utils/file_utils.py
> +def youtube_copy(youtube_url: str, output: str) -> str:
> I think my general comment is that I think this function should be folded into resource_copy? Maybe keep it as a separate function for now but use the function in resource_copy so that that single function can be used to fetch all sorts of content.

Good point, forgot about `resource_copy`. I like the idea more of keeping the function separate but using it inside of `resource_copy`.

2022-02-27 06:45 UTC, Shak2000 commented on cdp_backend/utils/file_utils.py
> +def youtube_copy(youtube_url: str, output: str) -> str:
I changed the parameters' names to be identical to those in `resource_copy`. In my case, `dst` is guaranteed to exist since it is called from `resource_copy`. If we want to assume it's not guaranteed, then it might be better to transfer the code that makes up `youtube_copy` to `resource_copy` since I would need to duplicate the code if `dst` were empty.

2022-02-28 16:56 UTC, JacksonMaxfield commented on cdp_backend/utils/file_utils.py
> +        if uri.find("https://www.youtube.com/embed/") == 0:
Hah. Wow, our bad @Shak2000, we both reviewed this and didn't realize it was in the `resource_copy` function already.

That said, I think my prior statement of "checking for all the various youtube link types" still stands.

2022-02-28 16:58 UTC, JacksonMaxfield commented on cdp_backend/utils/file_utils.py
> +def youtube_copy(youtube_url: str, output: str) -> str:
I _think_ I am okay with leaving `dst` as required then. When running this function on any youtube video, what is the produced file name?

2022-03-01 04:22 UTC, Shak2000 commented on cdp_backend/utils/file_utils.py
> +def youtube_copy(youtube_url: str, output: str) -> str:
If the video is not embedded, the file name would be the section of the YouTube video URL after `watch?v=`. For example, if the video URL is `https://www.youtube.com/watch?v=lheapd7bgLA`, the file name would be `lheapd7bgLA.mp4`.

If the video is embedded, the file name would be the section of the YouTube video URL after `embed/`. For example, if the video URL is `https://www.youtube.com/embed/JTW-jJzmPzQ`, the file name would be `JTW-jJzmPzQ`.

I chose this strategy since I know that YouTube always generates unique ID's for its videos.

I will soon update this pull request to accommodate these changes.

2022-03-01 04:26 UTC, JacksonMaxfield commented on cdp_backend/utils/file_utils.py
> +def youtube_copy(youtube_url: str, output: str) -> str:
Perfect. That works for me.

2022-03-05 18:05 UTC, JacksonMaxfield approved these changes
One minor nitpick but everything else looks perfect. Thanks for making the changes!

2022-03-05 18:05 UTC, JacksonMaxfield commented on cdp_backend/utils/file_utils.py
> +        if "=" in str(uri):
Nitpick: can we be even more specific here? does split by `v=` work?

And a comment that says "split by youtube video query parameter"

2022-03-06 01:43 UTC, isaacna approved these changes

2022-03-06 01:46 UTC, JacksonMaxfield commented on cdp_backend/utils/file_utils.py
> +    dst = Path(str(dst) + ".mp4")
Was about to merge but one last look I think catches this.

This will always overwrite the supplied `dst` correct?

I think there simply needs to be an `if dst is not None` before this statement.

Additionally the docstring / parameter typing should be updated to `dst: Optional[Path] = None`

2022-03-06 03:50 UTC, Shak2000 commented on cdp_backend/utils/file_utils.py
> +    dst = Path(str(dst) + ".mp4")
No, I assumed that `dst` is not empty since if `dst` is `None`, it would be a assigned a value, as seen [here](https://github.com/Shak2000/cdp-backend/blob/91fc71f7b5726b763715e385607436279177e32f/cdp_backend/utils/file_utils.py#L88). I can throw an exception if `dst` is `None` though. WDYT?

2022-03-06 03:52 UTC, JacksonMaxfield commented on cdp_backend/utils/file_utils.py
> +    dst = Path(str(dst) + ".mp4")
Ohhhh i see what you are doing. Yes. My mistake. Okay so then only nitpick would be instead of doing this `str(dst) + ".mp4"` string addition. `Path` has a function called `with_suffix` that is "safer" imo.

```python
Path(str(dst)).with_suffix(".mp4")
```

2022-03-06 03:53 UTC, JacksonMaxfield commented on cdp_backend/utils/file_utils.py
> +    dst = Path(str(dst) + ".mp4")
But yes, you are correct. My mistake on on the overwrite vs simply adding the mp4

2022-03-06 04:11 UTC, Shak2000 commented on cdp_backend/utils/file_utils.py
> +    dst = Path(str(dst) + ".mp4")
I just pushed a new change based on your feedback.

2022-03-06 04:24 UTC, merged