feature/model-validator-fix-and-update
CouncilDataProject/cdp-backend pull request #32
Opened 2020-12-19 17:58 UTC by isaacna

* Fixed query building bug when primary key is another Model/ReferenceField

* Create class for validation output and add conflicting model results

**Pull request recommendations:**
- [x] Name your pull request _your-development-type/short-description_. Ex: _feature/read-tiff-files_
- [ ] Link to any relevant issue in the PR description. Ex: _Resolves [gh-12], adds tiff file format support_
- [x] Provide context of changes.
 - Query was erroring out in `is_model_unique` when we were filtering by a `ReferenceField` (when querying something like `Event` which has `Body` as a primary key.
 - Fixed how we build the query because the way that the queries are built for `fireo` [is different when you want to filter by a `ReferenceField`](https://octabyte.io/FireO/querying-data/querying-and-filtering/#filter-with-reference-model), and this was only [recently added in 1.3.7](https://github.com/octabytes/FireO/releases/tag/v1.3.7). 
 - Added `UniquenessValidation` object because in the event gather pipeline we want to retrieve the existing db model(s) if it exists (Ex. if `Body` exists, we want to use that model as a `ReferenceField` in the `Event`). This way we can properly build the db models bottom-up from the ingestion models.
- [x] Provide relevant tests for your feature or bug fix.
 - Added test case for `Event` since it has a `ReferenceField` primary key
 - Manually tested that this works
- [x] Provide or update documentation for any feature added by your pull request.

Thanks for contributing!

2020-12-19 18:24 UTC, JacksonMaxfield approved these changes
This is such a good catch!

Specifically related to this PR, can you version bump `fireo` in dependencies to be `~=1.3.7` to make sure it will always install correctly.

Regarding pulumi preview. I know it's not related to this PR but could you as a part of this PR just remove [this section](https://github.com/CouncilDataProject/cdp-backend/blob/main/.github/workflows/check-pr.yml#L86) of the check-pr workflow.

This should fix the PR checks. It's failing because your fork of the library doesn't have the pulumi credentials.

2020-12-19 18:24 UTC, JacksonMaxfield commented on cdp_backend/database/validators.py
> +    """
Should just be `Parameters` in docstring no?

2020-12-19 18:55 UTC, JacksonMaxfield requested changes

2020-12-19 18:55 UTC, JacksonMaxfield commented on cdp_backend/database/validators.py
> +def model_is_unique(model: Model) -> UniquenessValidation:
I would change this function name to `get_model_uniqueness` or similar. The `*_is_*` naming pattern is specific to when a boolean is returned.

Related, you will need to update this docstring to say:
```python
"""
Examples
--------
>>> from cdp_backend.database import models
... from cdp_backend.database.validators import get_model_uniqueness
...
... b = models.Body.Example()
... b_unique = get_model_uniqueness(b)
... if b_unique.is_unique:
...     b.save()
"""
```

2020-12-20 02:54 UTC, isaacna commented on cdp_backend/database/validators.py
> +def model_is_unique(model: Model) -> UniquenessValidation:
Good catch I missed that

2020-12-20 23:07 UTC, JacksonMaxfield commented on cdp_backend/database/validators.py
> +    """
Last change is to put the parameters into the normal format:
```python
"""
Parameters
----------
is_unique: bool
    ...

conflicting_models: List[Model]
    ...
"""
```

2020-12-20 23:08 UTC, JacksonMaxfield approved these changes
Once the `Parameters` docstring is fixed feel free to merge whenever.

2020-12-20 23:35 UTC, isaacna commented on cdp_backend/database/validators.py
> +    """
oops missed that, fixed

2020-12-20 23:41 UTC, merged