Feature/event gather pipeline minimal db upload
CouncilDataProject/cdp-backend pull request #33
Opened 2020-12-21 05:23 UTC by isaacna

**Pull request recommendations:**
- [x] Name your pull request _your-development-type/short-description_. Ex: _feature/read-tiff-files_
- [x] Link to any relevant issue in the PR description. Ex: _Resolves [gh-12], adds tiff file format support_
 - Incremental work of #16 
- [x] Provide context of changes.
 - Started the event gather pipeline but doing it incrementally for feedback to avoid too large of a PR 
 - This only covers the "upload to database" part of the pipeline, and only for a minimal event (body and sessions). I plan on having separate PR's for the audio/transcript creation and marked with TODO's accordingly
 - Used `example_get_events_func` to make testing easier and as a placeholder, but I'm assuming we want to pass the callable function some other way for different deployments later. Is there an easy way to do this via command line args?
- [x] Provide relevant tests for your feature or bug fix.
 - I thought it would be pretty complicated/not necessary to write end-to-end tests with all the interactions that don't necessarily return anything at the end, so I plan on writing tests mostly at the task level, but lmk if you think otherwise
 - manually tested this with my personal firestore app
- [ ] Provide or update documentation for any feature added by your pull request.

Thanks for contributing!

2020-12-21 05:25 UTC, isaacna commented on cdp_backend/pipeline/event_gather_pipeline.py
> +from datetime import datetime
Forgot:
```
#!/usr/bin/env python
# -*- coding: utf-8 -*-
```
I'll add that on the next commit

2020-12-22 04:41 UTC, JacksonMaxfield requested changes
Overall, looking real solid. I love how simple the fireo stuff becomes. And the business logic generally makes sense so far!

2020-12-22 04:41 UTC, JacksonMaxfield commented on cdp_backend/bin/event_gather.py
> +            prog="event_gather",
Prefix with `cdp` -> `cdp_event_gather`.

2020-12-22 04:41 UTC, JacksonMaxfield commented on cdp_backend/bin/event_gather.py
> +            description="Gather events through running the pipeline.",
I would change to `"Gather, process, and store event data to CDP infrastructure."`

2020-12-22 04:41 UTC, JacksonMaxfield commented on cdp_backend/bin/event_gather.py
> +            help="Path to the google credentials file.",
Can you add that this is specifically a "Google Service Account Credentials JSON"

2020-12-22 04:41 UTC, JacksonMaxfield commented on cdp_backend/bin/event_gather.py
> +        p.add_argument(
Need to add an argument that is "path to `get_events` function file"

2020-12-22 04:41 UTC, JacksonMaxfield commented on cdp_backend/bin/event_gather.py
> +def example_get_events_func() -> List[EventIngestionModel]:
This function should live in a separate file and should be read in using some sort of importlib + filepath  + finding `get_events`

2020-12-22 04:41 UTC, JacksonMaxfield commented on cdp_backend/bin/event_gather.py
> +        flow.run()
Still debating. I think maybe this is determined with arguments. I.e. default it runs synchronously (like current) but on backfill jobs it runs w/ dask or something? Don't change anything for now just thinking about it.

2020-12-22 04:41 UTC, JacksonMaxfield commented on cdp_backend/pipeline/event_gather_pipeline.py
> +        events: List[EventIngestionModel] = get_events_func()
Woah, didn't know you could type returns like that. I assume `mypy` enforced this? I personally like it.

2020-12-22 04:41 UTC, JacksonMaxfield commented on cdp_backend/pipeline/event_gather_pipeline.py
> +            process_event(event)
We could `map` this but we commonly run into race conditions with `ThreadPoolExecutor` as it is now so going to say "sadly, for loop is the way to go"

2020-12-22 04:41 UTC, JacksonMaxfield commented on cdp_backend/pipeline/event_gather_pipeline.py
> +            process_event(event)
That said. I think this `process_event` -> `upload_to_database` -> `upload_body` -> etc. is a bit odd.

I would have all of the final children tasks live in this loop.

I.E.
```python
for event in events:
    body_ref = upload_body(event.body)
    event_ref = upload_event(event, body_ref)
    for session in event.sessions:
        upload_session(session)
```

2020-12-22 04:41 UTC, JacksonMaxfield commented on cdp_backend/pipeline/event_gather_pipeline.py
> +    upload_to_database(event)
These todos should be their own `@task` declarations imo.

2020-12-22 04:41 UTC, JacksonMaxfield commented on cdp_backend/pipeline/event_gather_pipeline.py
> +    event_ref = upload_event(event, body_ref)
There is a part of me that wants to split out some of the logic contained in these `upload_*` tasks. I.E. separation of getting the first / earliest datetime session and applying that datetime to the event itself. Thoughts?

My reasoning would be easier testing so that you don't need to mock database interactions on simply business logic.

2020-12-22 04:41 UTC, JacksonMaxfield commented on cdp_backend/pipeline/event_gather_pipeline.py
> +        db_body.external_source_id = body.external_source_id
This is a perfect example of my above comment about separation of business logic vs upload management. This could be tested really easily without mocking uploads imo.

2020-12-22 04:41 UTC, JacksonMaxfield commented on cdp_backend/pipeline/event_gather_pipeline.py
> +        db_body.external_source_id = body.external_source_id
Maybe make these functions be `create_body_from_ingestion_model` and `create_event_from_ingestion_model`, etc.

2020-12-22 04:41 UTC, JacksonMaxfield commented on cdp_backend/pipeline/event_gather_pipeline.py
> +        return uniqueness_validation.conflicting_models[0]
This then further frees up this code to be a general `handle_model_upload` task that tasks some model and handles the exception because I see you are duplicating this code a bit.

2020-12-22 04:41 UTC, JacksonMaxfield commented on cdp_backend/pipeline/event_gather_pipeline.py
> +        return uniqueness_validation.conflicting_models[0]
Same business logic and upload operation separation comments here.

2020-12-22 04:41 UTC, JacksonMaxfield commented on cdp_backend/tests/pipeline/test_event_gather_pipeline.py
> +        assert db_body.is_active == ingestion_body.is_active
After changes come in for business logic separation you can add tests for all the optional + required parameter mutations and then a single one for model upload.

2020-12-22 04:41 UTC, JacksonMaxfield commented on cdp_backend/tests/pipeline/test_event_gather_pipeline.py
> +        assert isinstance(flow, Flow)
Note to self: Create a bin script to generate the flow visualization to attach to documentation after this / other PRs merge like the current doc generation scripts.

2020-12-22 04:41 UTC, JacksonMaxfield commented on setup.py
> +    "prefect==0.13.0"
They just released a new 0.14.0 version is shouldn't affect this PR but would be nice to use if possible.

Can we safely change this to `prefect~=0.14.0`

2020-12-22 04:41 UTC, JacksonMaxfield commented on setup.py
> +            "event_gather=cdp_backend.bin.event_gather:main",
Related to first comment: prefix with `cdp` -> `cdp_event_gather`

2020-12-22 19:20 UTC, tohuynh commented on cdp_backend/pipeline/event_gather_pipeline.py
> +    upload_to_database(event)
Wouldn't this make `processs_event` a flow? `@task` are discrete actions of a flow right?

2020-12-22 19:20 UTC, tohuynh commented on cdp_backend/pipeline/event_gather_pipeline.py
> +    event_ref = upload_event(event, body_ref)
I agree with Jackson. That's a good idea.

2020-12-22 19:20 UTC, tohuynh commented on cdp_backend/pipeline/event_gather_pipeline.py
> +            process_event(event)
Another note: create/get transcript and create/get audio todos are for sessions. I think we'd still need a `a process_session`.

2020-12-22 19:21 UTC, JacksonMaxfield commented on cdp_backend/pipeline/event_gather_pipeline.py
> +            process_event(event)
I believe that will come in the "next PR"

2020-12-22 19:22 UTC, JacksonMaxfield commented on cdp_backend/pipeline/event_gather_pipeline.py
> +    upload_to_database(event)
Yes each @task is a discrete step in the workflow which is also why I want to bring them to the top level.

2020-12-22 23:00 UTC, isaacna commented on cdp_backend/pipeline/event_gather_pipeline.py
> +        events: List[EventIngestionModel] = get_events_func()
Yeah I find doing this pretty helpful just for writing code itself, wouldn't mind making it standard practice

2020-12-22 23:14 UTC, isaacna commented on cdp_backend/pipeline/event_gather_pipeline.py
> +            process_event(event)
Maybe my understanding of prefect was wrong, but I thought since the the tasks in each iteration of the for loop are independent of each other, prefect "magic" would handle that properly when generating the DAG and run tasks in parallel if we chose an executor like dask. 

Also it looks like prefect has some mapping examples that I think we can do instead of the for loop: https://docs.prefect.io/core/concepts/mapping.html#prefect-approach

Also, are there race conditions across mulitple event processes that I'm missing? Do you men the potential of 2 events modifying a shared document like `Body` or something?

2020-12-22 23:16 UTC, isaacna commented on cdp_backend/pipeline/event_gather_pipeline.py
> +            process_event(event)
And yeah I was planning on handling the transcript/audio at a session level in the next PR, but put it in the process_event comments for now.

Yeah I may have over modularized the upload code, I can simplify that a bit

2020-12-22 23:19 UTC, JacksonMaxfield commented on cdp_backend/pipeline/event_gather_pipeline.py
> +            process_event(event)
You are correct in that you are constructing a DAG here and that yes prefect "magic" will unpack the for loop for us! My bad in my thinking!

But I wouldn't use a non-synchronous executor for this specific workflow unless the user is backfilling a lot of events because exactly like you mentioned there exists race conditions not common for `Body` but very common for minutes items. Currently (in `cdptools`) we treat each session as it's own event and as such if two events are being uploaded in parrallel it's pretty common to have a race condition for `MinutesItem` or `Matter` documents.

2020-12-22 23:25 UTC, isaacna commented on cdp_backend/pipeline/event_gather_pipeline.py
> +    upload_to_database(event)
Are we trying to make each instance of processing a single event a flow? The way I was approaching it was that the flow is the multiple instances of processing an event, and a single `process_event` call is not a flow itself. `process_event` is just a container method (for readability) and sets the tasks for each event we are trying to process, and then we rely on prefect to determine the workflow and what tasks are dependent on each other. 

Does bringing the tasks to the top level change the functionality at all or is it just a prefect coding standard thing?

2020-12-22 23:27 UTC, isaacna commented on cdp_backend/pipeline/event_gather_pipeline.py
> +    event_ref = upload_event(event, body_ref)
Yeah good point, I think that's the right call and will make the testing much easier

2020-12-22 23:30 UTC, JacksonMaxfield commented on cdp_backend/pipeline/event_gather_pipeline.py
> +    upload_to_database(event)
No don't make `process_event` it's own flow. You had the right idea here in that this is all just DAG definition I just don't like the styling of having a container of prefect tasks is all. I think the flow defintion should have everything in it without any "multi-task containers" basically.

2020-12-22 23:31 UTC, JacksonMaxfield commented on cdp_backend/pipeline/event_gather_pipeline.py
> +        events: List[EventIngestionModel] = get_events_func()
I can see this being useful for specifically "functions or callables imported from some other library" but if the function is defined in the same file I think it may be overkill. But yea. definitely nice.

2020-12-24 22:36 UTC, isaacna commented
Not sure why the infrastructure tests are still failing.

It looks like the mypy checks are also failing due to how I am unit testing the tasks. I think I know what the issue is but I've asked a question in the prefect community just to make sure: https://github.com/PrefectHQ/prefect/discussions/3896

2020-12-26 23:45 UTC, isaacna commented
I ignored the mypy tests that were failing on some of the prefect lines. I think I know what the issue but I brought it up here too: https://github.com/PrefectHQ/prefect/discussions/3896

I still don't fully understand why the pulumi test was failing, but from looking into it a bit I think it was because `@pulumi.runtime.test` actually initializes an asyncio event loop to run the test in, and for some reason importing prefect in one of the later files like `test_cdp_event_gather_pipeline` was causing the the asynchronous tasks that pulumi generates internally to be attached to a different event loop. Importing prefect into the `infrastructure/__init__.py` fixed this for me

2020-12-27 03:22 UTC, JacksonMaxfield requested changes
This is looking much better!

More minor changes and some discussions.

2020-12-27 03:22 UTC, JacksonMaxfield commented on cdp_backend/pipeline/cdp_event_gather_pipeline.py
> +        return uniqueness_validation.conflicting_models[0]
There is an interesting decision to make here. I think I said in documentation somewhere that if the document already exists the db, and the non-primary fields are different from how they are currently stored, it would update the fields that aren't primary keys. (Change in body description for example). Not quite sure how to do that.... I know each model definition has the primary keys labeled so it would be possible to check that the found model has different non-primary field values and then update and resave?

Idk, thoughts here would be nice. @tohuynh too.

2020-12-27 03:22 UTC, JacksonMaxfield commented on cdp_backend/pipeline/cdp_event_gather_pipeline.py
> +    db_event.event_datetime = event.sessions[0].session_datetime
Because there can be a session index on each session model, and the zeroth session isn't guaranteed to be the datetime earliest, can you do a list comprehension to find the earliest one and use that? (I don't think we would ever have a multi-day event but :shrug: never know)

2020-12-27 03:22 UTC, JacksonMaxfield commented on cdp_backend/pipeline/cdp_event_gather_pipeline.py
> +        # Is this how we want to handle when session_index isn't provided?
No, if no session index isn't provided it should be the index of the session in the parent list. Which means you will probably need to do a pre-process step on the whole session list prior to this task.

2020-12-27 03:22 UTC, JacksonMaxfield commented on setup.py
> +    "prefect==0.14.0"
Make this specifically `~=` instead of `==`.

2020-12-27 03:22 UTC, JacksonMaxfield commented on cdp_backend/tests/pipeline/test_cdp_event_gather_pipeline.py
> +            assert getattr(expected_db_model, field) == getattr(actual_db_model, field)
Can you move these to be near the top of the file or at least above where they are used in the tests, was a bit confused as to where they came from haha.

2020-12-27 03:23 UTC, JacksonMaxfield commented
> I ignored the mypy tests that were failing on some of the prefect lines. I think I know why this happens but I brought it up here too: [PrefectHQ/prefect#3896](https://github.com/PrefectHQ/prefect/discussions/3896)
> 
> I still don't fully understand why the pulumi test was failing, but from looking into it a bit I think it was because `@pulumi.runtime.test` actually initializes an asyncio event loop to run the test in, and for some reason importing prefect in one of the later files like `test_cdp_event_gather_pipeline` was causing the the asynchronous tasks that pulumi generates internally to be attached to a different event loop. Importing prefect into the `infrastructure/__init__.py` fixed this for me

Yea I have scene some incredible event loop testing due to similar issues. Never with Prefect though. Hopefully someone responds to the discussion post you had. But it's over break -- if no one responds in a couple of days I will post to their Slack.

2020-12-27 04:16 UTC, isaacna commented on cdp_backend/pipeline/cdp_event_gather_pipeline.py
> +        return uniqueness_validation.conflicting_models[0]
Sounds good, updating the non-primary fields shouldn't too bad. I think I can just loop through the ingestion model fields and if the found db model differs, update those fields and overwrite.

The other thing I defaulted to was returning the first model, but should we consider what to do if there's more than one? That would be assuming our db has bad data, but that shouldn't happen if this script is the only source of event gathering, or if a race condition appears if we try to parallelize stuff

2020-12-27 04:17 UTC, isaacna commented on cdp_backend/pipeline/cdp_event_gather_pipeline.py
> +    db_event.event_datetime = event.sessions[0].session_datetime
Works for me, I just made that assumption but can change it just to be safe

2020-12-27 04:24 UTC, isaacna commented on cdp_backend/pipeline/cdp_event_gather_pipeline.py
> +        # Is this how we want to handle when session_index isn't provided?
> the index of the session in the parent list 

By this do you mean it's actual list index in the parent event's `sessions` list? 

For this ppre-processing logic, in the case that session_index is provided on some of the `session` ingestion models but not the others, do we want to go off the actual `session_index` values or the list indices?

2020-12-27 07:18 UTC, JacksonMaxfield commented on cdp_backend/pipeline/cdp_event_gather_pipeline.py
> +        return uniqueness_validation.conflicting_models[0]
I thought about that too. I would say adding a check for if the length of the returned conflicting models list is greater than 1 and raising an error makes sense to me.

2020-12-27 07:29 UTC, JacksonMaxfield commented on cdp_backend/pipeline/cdp_event_gather_pipeline.py
> +        # Is this how we want to handle when session_index isn't provided?
> By this do you mean it's actual list index in the parent event's `sessions` list?

Yep!

---

Here is how I would do the indexing logic in the mixed index and no index provided case.

If the session index is available / provided, use it. If not, use the list item index. To do so, and this isn't efficient but hey this isn't algorithms class, I would make a list of None's that is of length of `max([len(sessions), max_session_index])` then fill in the indexes that are provided, then replace None in the list with sessions that don't have specific session indexes, then just remove all extra Nones.

---

After typing that out, maybe we just remove the `session_index` from the ingestion model and say that we will create `session_index` in the database solely off of list index...........

2020-12-27 21:45 UTC, isaacna commented on cdp_backend/pipeline/cdp_event_gather_pipeline.py
> +        return uniqueness_validation.conflicting_models[0]
Works for me

2020-12-27 22:00 UTC, isaacna commented on cdp_backend/pipeline/cdp_event_gather_pipeline.py
> +        # Is this how we want to handle when session_index isn't provided?
I'm good with implementing the above logic, I still would preferable to keep `session_index` in the ingestion model in case different implementations on the scraper side make using the order of the list unreliable, like threading over each session

2020-12-27 23:16 UTC, tohuynh commented on cdp_backend/pipeline/cdp_event_gather_pipeline.py
> +        # Is this how we want to handle when session_index isn't provided?
We could always just use the required `datetime` field to infer the sessions' indices. If the list of sessions has one or more missing `session_index`, use the `datetime` field to sort the list and then use the list item indices.

2020-12-28 22:32 UTC, JacksonMaxfield commented on cdp_backend/pipeline/cdp_event_gather_pipeline.py
> +        # Is this how we want to handle when session_index isn't provided?
Sounds good to me! I hadn't thought of using the datetime but that would make sense... at least in the case that no one submits an event with multiple sessions starting at the same datetime.

2020-12-29 19:17 UTC, isaacna commented on cdp_backend/pipeline/cdp_event_gather_pipeline.py
> +        # Is this how we want to handle when session_index isn't provided?
Only thing about sorting by datetime is that at least for [Seattle](http://www.seattlechannel.org/BudgetCommittee), sessions can happen on the same day and from what I can tell the inferre datetime from scraping doesn't get more detailed than day-level.  

So maybe when `session_index` is missing for some, we start a partial list sorted by session_index, and then for the remaining sessions sort by datetime and then append them to that list? 

I think we should prioritize `session_index` first since that's usually explicitly derived from the html. I think the case where the provided `session_index` contradicts the event datetime is pretty unlikely, and in that case that I think that issue should be more on how the scraper is setting that data.

2020-12-29 19:33 UTC, isaacna commented on cdp_backend/pipeline/cdp_event_gather_pipeline.py
> +        db_body.start_datetime = body.start_datetime
I'm fine with doing the one liner or keeping them on separate lines. I personally prefer separate lines slightly more out of habit because I'm used to non-Python, but either works for me. @JacksonMaxfield any preference for coding style?

2020-12-29 19:34 UTC, isaacna commented on cdp_backend/pipeline/cdp_event_gather_pipeline.py
> +        db_session.session_index = session.session_index
oh that's a really good catch I didn't notice that edge case

2020-12-29 21:52 UTC, JacksonMaxfield commented on cdp_backend/pipeline/cdp_event_gather_pipeline.py
> +        # Is this how we want to handle when session_index isn't provided?
Yea I think the sort order should be `session_index` first, then `session_datetime`. But also, because I can't remember if we talked about it, did we ever discuss just making `session_index` required in the ingestion model? That would resolve all of these issues imo.

2020-12-29 21:53 UTC, JacksonMaxfield commented on cdp_backend/pipeline/cdp_event_gather_pipeline.py
> +        db_body.start_datetime = body.start_datetime
I personally prefer the elongated form that is currently there. Seen both one liner form and elongated forms many-a-time, and neither one bothers me, so really your call.

2021-01-02 18:16 UTC, isaacna commented on cdp_backend/pipeline/cdp_event_gather_pipeline.py
> +        # Is this how we want to handle when session_index isn't provided?
I agree, I'll just make `session_index` required. I think this is a better call since this logic should already be determined from the event providing function side imo.

2021-01-02 18:27 UTC, JacksonMaxfield commented on cdp_backend/bin/cdp_event_gather.py
> +        # TODO make the flow run on a certain type of Executor?
Can you remove this comment for now. Sorry nitpicky but :shrug:

2021-01-02 18:27 UTC, JacksonMaxfield commented on cdp_backend/bin/create_ingestion_model_doc.py
> +        filled_event_data=pformat(filled_event_data, sort_dicts=False),  # type: ignore
I am somewhat surprised that `mypy` is complaining here.... can you post the error log if you remove just these type ignores?

2021-01-02 19:12 UTC, isaacna commented on cdp_backend/bin/create_ingestion_model_doc.py
> +        filled_event_data=pformat(filled_event_data, sort_dicts=False),  # type: ignore
Yeah, I suddenly started getting the following:
```
cdp_backend/bin/create_ingestion_model_doc.py:84: error: Unexpected keyword argument "sort_dicts" for "pformat"
cdp_backend/bin/create_ingestion_model_doc.py:87: error: Unexpected keyword argument "sort_dicts" for "pformat"
```

I cleaned my project and re-installed all dependencies, so maybe the pprint module got updated?

2021-01-02 19:12 UTC, isaacna commented on cdp_backend/bin/cdp_event_gather.py
> +        # TODO make the flow run on a certain type of Executor?
Will do, will remove that in my upcoming set of changes

2021-01-02 19:45 UTC, JacksonMaxfield commented on cdp_backend/bin/create_ingestion_model_doc.py
> +        filled_event_data=pformat(filled_event_data, sort_dicts=False),  # type: ignore
Huh. `pprint` is a standard library module so would be surprised if it changed on a patch but I did look up the docs and saw that it didn't have the `sort_dicts` param until py38, so maybe this error occurred in py37?

2021-01-02 19:58 UTC, isaacna commented on cdp_backend/bin/create_ingestion_model_doc.py
> +        filled_event_data=pformat(filled_event_data, sort_dicts=False),  # type: ignore
Oh yeah that's probably it, on my machine I recently switched to using py37. I should be good to remove these then since the lint checker runs on py38

2021-01-02 20:15 UTC, isaacna commented
Some notes on these changes:
- Added back in the `UniquenessError` to use for cases where num conflicting models > 1. I throw this error on the pipeline side rather than the validator itself so that we can use the conflicting models for something else without throwing error (ex. a script to fix docs with duplicate primary keys)
- Passed in the db key as part of the `update_db_model` method bc when we pass a `Model` in by parameter fireo treats it as a temporary doc and removes it's key/id
- The `assert_db_models_equality` is to check db models for equivalence while ignoring some of the fireo boilerplate stuff

2021-01-02 20:48 UTC, JacksonMaxfield approved these changes
These changes are great!

Some minor changes / nitpicks to get to and then feel free to merge. I am going to quickly merge in an admin PR to the repo that would awesome if you merged into this branch and made sure everything works.

2021-01-02 20:48 UTC, JacksonMaxfield commented on cdp_backend/bin/cdp_event_gather.py
> +            ),
Can you make this a standard name like `cdp-dev-infra-creds.json`. This is so specific to yours haha.

2021-01-02 20:48 UTC, JacksonMaxfield commented on cdp_backend/pipeline/cdp_event_gather_pipeline.py
> +            # Make sure we don't overwrite with empty values (or should we allow this?)
I strongly agree that `None` simply means keep the same. So yea, excluding `None` is the right call here.

2021-01-02 20:48 UTC, JacksonMaxfield commented on cdp_backend/pipeline/cdp_event_gather_pipeline.py
> +            # Make sure we don't overwrite with empty values (or should we allow this?)
Can you add that to the actual ingestion models documentation page actually.

2021-01-02 20:48 UTC, JacksonMaxfield commented on cdp_backend/pipeline/cdp_event_gather_pipeline.py
> +                log.info(f"Updating {db_key} {field} from {db_val} to {ingestion_val}.")
Beautiful.

2021-01-02 20:48 UTC, JacksonMaxfield commented on cdp_backend/pipeline/cdp_event_gather_pipeline.py
> +    return db_model
Love this new decision flow.

2021-01-02 20:48 UTC, JacksonMaxfield commented on cdp_backend/tests/pipeline/test_cdp_event_gather_pipeline.py
> +import pytest
Nitpick: I think in my prior comment I asked to make the imports in the pipeline module relative.

In the source files, relative imports are preferred, in the test modules fully qualified are preferred.
So here they should be back to fully qualified.

Idk, Python :shrug: 

Also, can you run:

```bash
pip install isort
isort --recursive
black .
```

This will clean up the import sort order (not the relative vs fully qualified, but just the sort order)
If you use vscode I would drop this into your settings.json as it will make it so that when you save a python file it will auto sort the imports:
```
"[python]": {
        "editor.codeActionsOnSave": {
            "source.organizeImports": true
        }
    }
```

2021-01-02 20:48 UTC, JacksonMaxfield commented on cdp_backend/tests/pipeline/test_cdp_event_gather_pipeline.py
> +import pytest
I have a quick PR with some admin changes that if you merge into will have some isort additions to make it work well with black as well.

2021-01-02 22:26 UTC, isaacna commented on cdp_backend/tests/pipeline/test_cdp_event_gather_pipeline.py
> +import pytest
Sounds good, this is a helpful tool!

2021-01-02 22:26 UTC, isaacna commented on cdp_backend/bin/cdp_event_gather.py
> +            ),
Oh yeah my bad I accidentally left that in to make testing more convenient

2021-01-02 22:27 UTC, isaacna commented on cdp_backend/pipeline/cdp_event_gather_pipeline.py
> +            # Make sure we don't overwrite with empty values (or should we allow this?)
Will do

2021-01-02 22:29 UTC, isaacna commented on cdp_backend/pipeline/cdp_event_gather_pipeline.py
> +    return db_model
Thanks!

2021-01-02 22:53 UTC, merged